# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mindblurb - Technical Explorations
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Notes on various technical things including software, hardware and electronics
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mindblurb.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
keep: ".git"

host: 0.0.0.0
port: 4000

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      #permalink: /:categories/:year/:month/:day/:title/ #pretty
  -
    scope:
      path: "_posts/old"
      type: "posts"
    values:
      layout: "post"
      #permalink: /old-blog/:year/:month/:title/
      category: "old-blog"
